NestingChallengeInstaFreight/force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NestingChallengeInstaFreight/force-app/main/default/objects/Widget__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Created By Bonoshree on 19th Apr 2022</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NestingChallengeInstaFreight/force-app/main/default/classes/WidgetUpdateController.cls
/*======================================================================================================================================
*   Class Name : WidgetUpdateController
*   Author     : BMONDAL
*   Date       : 19-APR-2022
*   Test Class : WidgetUpdateControllerTest
*   Description:     
* =====================================================================================================================================  
*/
public with sharing class WidgetUpdateController {
  
    //@AuraEnabled annotation enables Lightning to access below apex method
    @AuraEnabled
    public static Boolean insertWidget(Widget__c widget) {
        Id currentUserProfileId = UserInfo.getProfileId();
        String profileName = [SELECT Name FROM Profile WHERE Id =: currentUserProfileId].Name;   // Get Profile Name 
        boolean success;
        
        // Condition to allow 'System Admin' and 'Widget Master' Profile users to save record even if value is not nested
        if(MatcherClass.isTextNested(widget.Value__c)){
            insert widget;
            success = true;
        }
        else{
            success = false;
        }
        return success;
    }
}