NestingChallengeInstaFreight/force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NestingChallengeInstaFreight/force-app/main/default/objects/Widget__c/fields/Is_Properly_Nested__c.field-meta.xml
<CustomField>
    <fullName>Is_Properly_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created  by Bonoshree on 19th Apr 2022</description>
    <label>Is Properly Nested</label>
    <type>Checkbox</type>
</CustomField>

NestingChallengeInstaFreight/force-app/main/default/objects/Widget__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Created By Bonoshree on 19th Apr 2022</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NestingChallengeInstaFreight/force-app/main/default/classes/CheckNestedValue_Batch.cls
/*======================================================================================================================================
*   Class Name : CheckNestedValue_Batch
*   Author     : BMONDAL
*   Date       : 19-APR-2022
*   Test Class : CheckNestedValue_BatchTest
*   Description: This class helps to update the Is_Properly_Nested__c field after checking if the Value__c is Properly Nested.        
* =====================================================================================================================================  
*/
global class CheckNestedValue_Batch implements Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {       // collect the batches of records or objects to be passed to execute
        //Return all widget records
        return Database.getQueryLocator('Select id, Value__c, Is_Properly_Nested__c, OwnerId From Widget__c where IsProcessed__c = false');  //WHERE Value__c = \'Bonoshree\'
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {     // process each batch of records
		// process each batch of records default size is 200
        for (sObject s : scope) {
            Widget__c obj = (Widget__c) s;
            if(!String.isBlank(obj.Value__c) && MatcherClass.isTextNested(obj.Value__c)) {
            	obj.Is_Properly_Nested__c = true;   // Update the Is_Properly_Nested__c field             
        	}
            
            obj.IsProcessed__c = true;
        }
        
        update scope;

    }
    global void finish(Database.BatchableContext bc) {       // execute any post-processing operations      	
        
   }  

}